/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./../../dashboard/app/app.vue')['default']
    ConfigSection: typeof import('./../../dashboard/app/components/ConfigSection.vue')['default']
    FleetSection: typeof import('./../../dashboard/app/components/FleetSection.vue')['default']
    LogsSection: typeof import('./../../dashboard/app/components/LogsSection.vue')['default']
    McpCard: typeof import('./../../dashboard/app/components/McpCard.vue')['default']
    McpLogsPanel: typeof import('./../../dashboard/app/components/McpLogsPanel.vue')['default']
    PortalSidebar: typeof import('./../../dashboard/app/components/PortalSidebar.vue')['default']
    PortalTopbar: typeof import('./../../dashboard/app/components/PortalTopbar.vue')['default']
    ProfilesSection: typeof import('./../../dashboard/app/components/ProfilesSection.vue')['default']
    Section: typeof import('./../../dashboard/app/components/Base/Section.vue')['default']
    SettingsSection: typeof import('./../../dashboard/app/components/SettingsSection.vue')['default']
    ToolsSection: typeof import('./../../dashboard/app/components/ToolsSection.vue')['default']
  }
}
