/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_getMcps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminHealthDto: {
            /** @enum {string} */
            status: "ok";
        };
        KeyValuePairDto: {
            key: string;
            value: string;
            masked?: boolean;
        };
        ManagedStdioMcpDefinitionDto: {
            id: string;
            name: string;
            enabled: boolean;
            autoStart: boolean;
            toolPrefix: string;
            startupTimeoutMs: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            transport: "stdio";
            command: string;
            args: string[];
            cwd?: string;
            env: components["schemas"]["KeyValuePairDto"][];
        };
        ManagedStreamableHttpMcpDefinitionDto: {
            id: string;
            name: string;
            enabled: boolean;
            autoStart: boolean;
            toolPrefix: string;
            startupTimeoutMs: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            transport: "streamable-http";
            url: string;
            headers: components["schemas"]["KeyValuePairDto"][];
        };
        ManagedToolDto: {
            name: string;
            upstreamName: string;
            title?: string;
            description?: string;
            inputSchema: {
                [key: string]: unknown;
            };
            outputSchema?: {
                [key: string]: unknown;
            };
            annotations?: {
                [key: string]: unknown;
            };
            execution?: {
                [key: string]: unknown;
            };
        };
        ManagedMcpSnapshotDto: {
            definition: components["schemas"]["ManagedStdioMcpDefinitionDto"] | components["schemas"]["ManagedStreamableHttpMcpDefinitionDto"];
            /** @enum {string} */
            status: "stopped" | "starting" | "ready" | "degraded" | "error" | "stopping";
            tools: components["schemas"]["ManagedToolDto"][];
            toolCount: number;
            pid: number | null;
            lastError?: string;
            updatedAt: string;
        };
        ManagedMcpCollectionDto: {
            items: components["schemas"]["ManagedMcpSnapshotDto"][];
            generatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminHealthDto"];
                };
            };
        };
    };
    AdminController_getMcps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedMcpCollectionDto"];
                };
            };
        };
    };
}
